name: build

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r2s'
        required: false

jobs:

  build:
    name: Build ${{ github.event.client_payload.device || github.event.inputs.device }}
    runs-on: ubuntu-18.04
    env:
      DEVICE: ${{ github.event.client_payload.device || github.event.inputs.device }}
      TG: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      DEPLOY_SSHKEY: ${{ secrets.SSH_KEY }}
    if: github.repository_owner=='klever1988'

    steps:

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo sysctl vm.swappiness=0
          nohup sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk &
          sudo -E apt update
          nohup sudo -E apt -y --no-install-recommends install jq build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf intltool rsync swig &

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Checkout
        run: |
          cd
          sudo curl -sL https://raw.githubusercontent.com/klever1988/nanopi-openwrt/zstd-bin/zstd | sudo tee /usr/bin/zstd > /dev/null
          for i in {1..10}
          do
            curl -sL --fail https://github.com/klever1988/sshactions/releases/download/cache/lede.$DEVICE.img.zst.0$i || break
          done | zstdmt -d -o lede.img || (truncate -s 20g lede.img && mkfs.btrfs -M lede.img)
          LOOP_DEVICE=$(losetup -f) && echo "LOOP_DEVICE=$LOOP_DEVICE" >> $GITHUB_ENV
          sudo losetup -P --direct-io $LOOP_DEVICE lede.img
          mkdir lede && sudo mount -o nossd,compress=zstd $LOOP_DEVICE lede
          if [ -d 'lede/.git' ]; then
          cd lede && git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote set-branches --add origin openwrt-18.06
          git fetch && git reset --hard origin/openwrt-18.06-k5.4 && git merge -X theirs --no-edit origin/openwrt-18.06
          else
          sudo chown $USER:$(id -gn) lede && (cd lede && git init && git remote add -t openwrt-18.06-k5.4 -f origin https://github.com/immortalwrt/immortalwrt && git checkout openwrt-18.06-k5.4)
          fi

      - name: Update feeds and packages
        run: |
          cd ~/lede
          if [ -d 'feeds' ]; then
            pushd feeds/packages; git restore .; popd
            pushd feeds/luci; git restore .; popd
          fi
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          . $GITHUB_WORKSPACE/patches.sh
          . $GITHUB_WORKSPACE/merge_packages.sh

      - name: Custom configure file
        run: |
          cd ~/lede
          cat $GITHUB_WORKSPACE/myr4s.seed > .config

      - name: Debug via tmate
        uses: klever1988/ssh2actions@main
        if: ${{ github.event.client_payload.debug == 'true' }}
        with:
          mode: ngrok
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
          SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
          NGROK_TOKEN: ${{secrets.NGROK_TOKEN}}

      - name: Compile firmware
        run: |
          cd ~/lede

          sed -i '/\(tools\|toolchain\)\/Makefile/d' Makefile
          echo -e '# CONFIG_SIGNED_PACKAGES is not set\n' >> .config

          make defconfig

          while true; do make download -j && break || true; done
          make -j$(($(nproc) + 1)) || make V=sc
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          cd
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          mkdir -p ./release
          cd lede
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ../artifact/firmware/; cp .config ../artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ../artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ../artifact/buildinfo/
          cp $(ls -1 ../artifact/firmware/*img*) ../release/$DEVICE.img.gz
          pushd ../release/ && md5sum $DEVICE.img.gz > md5sum.txt && popd
          echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "strDevice=$(echo $DEVICE | awk '{print toupper($0)}')" >> $GITHUB_ENV
          cd ..
          mv artifact release $GITHUB_WORKSPACE

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware/

      - name: Debug via tmate
        uses: klever1988/ssh2actions@main
        if: ${{ failure() }}
        with:
          mode: ngrok
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
          SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
          NGROK_TOKEN: ${{secrets.NGROK_TOKEN}}


      - name: Send tg notification
        uses: appleboy/telegram-action@master
        if: env.TG
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          args: The ${{env.DEVICE}} build ran completed at ${{job.status}}.

